# Generated by Django 3.0.5 on 2020-06-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='approved',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
