# Generated by Django 3.0.5 on 2020-10-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_research_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
