# Generated by Django 3.0.5 on 2020-10-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_time',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
