# Generated by Django 3.1.4 on 2021-03-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0004_auto_20201024_1712'),
        ('UserManagement', '0003_user_is_deleted'),
    ]

    operations = [
    ]
