# Generated by Django 3.0.5 on 2020-12-30 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generalOrder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GeneralOrder',
            new_name='GeneralOrderTable',
        ),
    ]
