# Generated by Django 3.0.5 on 2020-12-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalOrder', '0003_auto_20201230_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genordertable',
            name='additional_comments',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='genordertable',
            name='item_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='genordertable',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='genordertable',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='genordertable',
            name='student_name',
            field=models.CharField(max_length=50),
        ),
    ]
