# Generated by Django 3.0.5 on 2020-05-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labInterface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='refillNeeded',
            field=models.BooleanField(default=False),
        ),
    ]
