# Generated by Django 3.0.5 on 2020-05-06 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labInterface', '0002_post_refillneeded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
