# Generated by Django 3.0.5 on 2020-05-11 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelFeature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelreading',
            name='reading_value',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
