# Generated by Django 3.0.5 on 2020-05-06 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('current_quantity', models.IntegerField()),
                ('min_quantity', models.IntegerField()),
                ('refillNeeded', models.BooleanField(default=False)),
                ('isOrdered', models.BooleanField(default=False)),
                ('status', models.TextField(blank=True)),
            ],
        ),
    ]
