# Generated by Django 3.0.5 on 2020-05-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='InventoryItem',
        ),
    ]
