# Generated by Django 3.0.5 on 2020-06-10 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0002_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
