# Generated by Django 3.0.5 on 2020-05-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0002_auto_20200507_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='requested_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
