# Generated by Django 3.0.5 on 2020-06-10 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
        ('quickOrder', '0003_delete_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.TextField(default='Pending Approval')),
                ('requested_quantity', models.IntegerField(default=0)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_name', models.TextField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quickOrder.InventoryItem')),
                ('user', models.ForeignKey(on_delete=models.SET(0), to='UserManagement.User')),
            ],
        ),
    ]
