# Generated by Django 3.0.5 on 2020-06-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_name',
            field=models.TextField(default='Name'),
        ),
    ]
