# Generated by Django 3.0.5 on 2020-06-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0005_auto_20200610_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_name',
            field=models.TextField(default='Loading...'),
        ),
    ]
