# Generated by Django 3.0.5 on 2020-05-12 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0005_auto_20200512_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='item_id',
        ),
    ]
