# Generated by Django 3.0.5 on 2020-06-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0006_auto_20200611_1523'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
