# Generated by Django 3.0.5 on 2020-05-14 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0006_auto_20200512_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
