# Generated by Django 3.0.5 on 2020-06-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
        ('quickOrder', '0007_delete_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
