# Generated by Django 3.0.5 on 2020-05-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0007_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(default='Pending Approval'),
        ),
    ]
