# Generated by Django 3.0.5 on 2020-06-17 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0008_auto_20200611_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_ordered',
        ),
    ]
