# Generated by Django 3.0.5 on 2020-05-14 00:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0009_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 14, 0, 28, 23, 158098, tzinfo=utc)),
        ),
    ]
