# Generated by Django 3.0.5 on 2020-05-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0012_auto_20200519_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.TextField(default='Khusbu Patel'),
        ),
    ]
