# Generated by Django 3.0.5 on 2020-05-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickOrder', '0013_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.TextField(),
        ),
    ]
